name: Product Feedback
description: for sharing your feedback regarding a demo scenario or the tool in general
title: "[Product Feedback]: <REPLACE Description of the feedback>"
labels: ["feedback"]
assignees: 'petender'
body:
  - type: dropdown
    id: satisfaction
    attributes:
        label: Satisfaction
        description: Overall, how satisfied are you with Trainer-Demo-Deploy?
        options:
        - 1-Extremely Dissatisfied
        - 2-Dissatisfied
        - 3-Neither Satisfied nor Dissatisfied
        - 4-Satisfied
        - 5-Extremely Satisfied

  - type: input
    id: contact
    attributes:
        label: Contact Details
        description: (OPTIONAL) How can we get in touch with you if we need more info 😉?
        placeholder: ex. email@example.com
    validations:
        required: false

  - type: textarea
    id: Feedback 
    attributes:
        label: Describe the feedback 
        description: What would you improve 
        placeholder: Tell us what you see!
        

  - type: textarea
    id: Demo-Affected 
    attributes:
        label: Demo Applied to 
        description: If applicable, provide the name of the demo scenario
        placeholder: Demo name

  - type: textarea
    id: Screenshots
    attributes:
        label: Relevant screenshots
        description: Please copy and paste any relevant screenshots 📸
        value: paste here 😉 

